/**
 * @deprecated 타일 매칭 방식 수학 게임은 deprecated되었습니다.
 * 새로운 객관식 퀴즈 시스템은 src/systems/math/ 및 src/components/games/MathQuizGame.ts를 사용하세요.
 * 이 파일은 기존 G1(수박) 게임 호환성을 위해 유지됩니다.
 */
import type { MathLevelConfig } from './subjectConfig';

export const MATH_LEVELS: MathLevelConfig[] = [
  // ── 덧셈 1자리 Lv 1~7 ──────────────────────────────────────────────────────
  {
    id: 'math-add-single-1',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'single',
    levelIndex: 1,
    targetValue: 10,
    tileRange: [1, 9],
    boardCols: 4,
    boardRows: 4,
    targetPairs: 5,
    constraint: 'moves',
    constraintValue: 20,
    starThresholds: [0, 5, 10],
    baseScore: 100,
    comboBonus: 50,
  },
  {
    id: 'math-add-single-2',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'single',
    levelIndex: 2,
    targetValue: 10,
    tileRange: [1, 9],
    boardCols: 4,
    boardRows: 4,
    targetPairs: 7,
    constraint: 'moves',
    constraintValue: 22,
    starThresholds: [0, 5, 10],
    baseScore: 100,
    comboBonus: 50,
  },
  {
    id: 'math-add-single-3',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'single',
    levelIndex: 3,
    targetValue: 10,
    tileRange: [1, 9],
    boardCols: 4,
    boardRows: 5,
    targetPairs: 8,
    constraint: 'moves',
    constraintValue: 24,
    starThresholds: [0, 5, 10],
    baseScore: 100,
    comboBonus: 50,
  },
  {
    id: 'math-add-single-4',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'single',
    levelIndex: 4,
    targetValue: [8, 10],
    tileRange: [1, 9],
    boardCols: 4,
    boardRows: 5,
    targetPairs: { 8: 6, 10: 6 },
    constraint: 'moves',
    constraintValue: 26,
    starThresholds: [0, 5, 10],
    baseScore: 100,
    comboBonus: 50,
  },
  {
    id: 'math-add-single-5',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'single',
    levelIndex: 5,
    targetValue: 10,
    tileRange: [1, 9],
    boardCols: 5,
    boardRows: 5,
    targetPairs: 10,
    constraint: 'time',
    constraintValue: 60,
    starThresholds: [0, 15, 30],
    baseScore: 100,
    comboBonus: 50,
  },
  {
    id: 'math-add-single-6',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'single',
    levelIndex: 6,
    targetValue: [7, 10],
    tileRange: [1, 9],
    boardCols: 5,
    boardRows: 5,
    targetPairs: { 7: 5, 10: 5 },
    constraint: 'time',
    constraintValue: 70,
    starThresholds: [0, 15, 30],
    baseScore: 100,
    comboBonus: 50,
  },
  {
    id: 'math-add-single-7',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'single',
    levelIndex: 7,
    targetValue: 10,
    tileRange: [1, 9],
    boardCols: 5,
    boardRows: 6,
    targetPairs: 12,
    constraint: 'time',
    constraintValue: 80,
    starThresholds: [0, 15, 30],
    baseScore: 100,
    comboBonus: 50,
  },

  // ── 덧셈 2자리 Lv 8~14 (더미) ──────────────────────────────────────────────
  {
    id: 'math-add-double-8',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'double',
    levelIndex: 8,
    targetValue: 20,
    tileRange: [10, 19],
    boardCols: 4,
    boardRows: 4,
    targetPairs: 5,
    constraint: 'moves',
    constraintValue: 20,
    starThresholds: [0, 5, 10],
    baseScore: 150,
    comboBonus: 75,
  },
  {
    id: 'math-add-double-9',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'double',
    levelIndex: 9,
    targetValue: 30,
    tileRange: [10, 29],
    boardCols: 4,
    boardRows: 4,
    targetPairs: 6,
    constraint: 'moves',
    constraintValue: 22,
    starThresholds: [0, 5, 10],
    baseScore: 150,
    comboBonus: 75,
  },
  {
    id: 'math-add-double-10',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'double',
    levelIndex: 10,
    targetValue: 50,
    tileRange: [10, 49],
    boardCols: 4,
    boardRows: 5,
    targetPairs: 7,
    constraint: 'moves',
    constraintValue: 24,
    starThresholds: [0, 5, 10],
    baseScore: 150,
    comboBonus: 75,
  },
  {
    id: 'math-add-double-11',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'double',
    levelIndex: 11,
    targetValue: 100,
    tileRange: [10, 90],
    boardCols: 4,
    boardRows: 5,
    targetPairs: 8,
    constraint: 'moves',
    constraintValue: 26,
    starThresholds: [0, 5, 10],
    baseScore: 150,
    comboBonus: 75,
  },
  {
    id: 'math-add-double-12',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'double',
    levelIndex: 12,
    targetValue: 100,
    tileRange: [10, 90],
    boardCols: 5,
    boardRows: 5,
    targetPairs: 10,
    constraint: 'time',
    constraintValue: 70,
    starThresholds: [0, 15, 30],
    baseScore: 150,
    comboBonus: 75,
  },
  {
    id: 'math-add-double-13',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'double',
    levelIndex: 13,
    targetValue: [50, 100],
    tileRange: [10, 90],
    boardCols: 5,
    boardRows: 5,
    targetPairs: { 50: 5, 100: 5 },
    constraint: 'time',
    constraintValue: 80,
    starThresholds: [0, 15, 30],
    baseScore: 150,
    comboBonus: 75,
  },
  {
    id: 'math-add-double-14',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'double',
    levelIndex: 14,
    targetValue: 100,
    tileRange: [10, 90],
    boardCols: 5,
    boardRows: 6,
    targetPairs: 12,
    constraint: 'time',
    constraintValue: 90,
    starThresholds: [0, 15, 30],
    baseScore: 150,
    comboBonus: 75,
  },

  // ── 덧셈 3자리 Lv 15~20 (더미) ─────────────────────────────────────────────
  {
    id: 'math-add-triple-15',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'triple',
    levelIndex: 15,
    targetValue: 200,
    tileRange: [100, 199],
    boardCols: 4,
    boardRows: 4,
    targetPairs: 5,
    constraint: 'moves',
    constraintValue: 20,
    starThresholds: [0, 5, 10],
    baseScore: 200,
    comboBonus: 100,
  },
  {
    id: 'math-add-triple-16',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'triple',
    levelIndex: 16,
    targetValue: 500,
    tileRange: [100, 499],
    boardCols: 4,
    boardRows: 4,
    targetPairs: 6,
    constraint: 'moves',
    constraintValue: 22,
    starThresholds: [0, 5, 10],
    baseScore: 200,
    comboBonus: 100,
  },
  {
    id: 'math-add-triple-17',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'triple',
    levelIndex: 17,
    targetValue: 1000,
    tileRange: [100, 900],
    boardCols: 4,
    boardRows: 5,
    targetPairs: 7,
    constraint: 'moves',
    constraintValue: 24,
    starThresholds: [0, 5, 10],
    baseScore: 200,
    comboBonus: 100,
  },
  {
    id: 'math-add-triple-18',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'triple',
    levelIndex: 18,
    targetValue: 1000,
    tileRange: [100, 900],
    boardCols: 5,
    boardRows: 5,
    targetPairs: 8,
    constraint: 'time',
    constraintValue: 80,
    starThresholds: [0, 15, 30],
    baseScore: 200,
    comboBonus: 100,
  },
  {
    id: 'math-add-triple-19',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'triple',
    levelIndex: 19,
    targetValue: 1000,
    tileRange: [100, 900],
    boardCols: 5,
    boardRows: 5,
    targetPairs: 10,
    constraint: 'time',
    constraintValue: 90,
    starThresholds: [0, 15, 30],
    baseScore: 200,
    comboBonus: 100,
  },
  {
    id: 'math-add-triple-20',
    subject: 'math',
    operation: 'addition',
    digitLevel: 'triple',
    levelIndex: 20,
    targetValue: 1000,
    tileRange: [100, 900],
    boardCols: 5,
    boardRows: 6,
    targetPairs: 12,
    constraint: 'time',
    constraintValue: 100,
    starThresholds: [0, 15, 30],
    baseScore: 200,
    comboBonus: 100,
  },
  // ── 뺄셈 1자리 Lv 1~7
  { id: 'math-sub-single-1', subject: 'math', operation: 'subtraction', digitLevel: 'single', levelIndex: 1, targetValue: 3, tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 5, constraint: 'moves', constraintValue: 20, starThresholds: [0, 5, 10], baseScore: 100, comboBonus: 50 },
  { id: 'math-sub-single-2', subject: 'math', operation: 'subtraction', digitLevel: 'single', levelIndex: 2, targetValue: 4, tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 7, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 100, comboBonus: 50 },
  { id: 'math-sub-single-3', subject: 'math', operation: 'subtraction', digitLevel: 'single', levelIndex: 3, targetValue: 5, tileRange: [1, 9], boardCols: 4, boardRows: 5, targetPairs: 8, constraint: 'moves', constraintValue: 24, starThresholds: [0, 5, 10], baseScore: 100, comboBonus: 50 },
  { id: 'math-sub-single-4', subject: 'math', operation: 'subtraction', digitLevel: 'single', levelIndex: 4, targetValue: [3, 5], tileRange: [1, 9], boardCols: 4, boardRows: 5, targetPairs: { 3: 6, 5: 6 }, constraint: 'moves', constraintValue: 26, starThresholds: [0, 5, 10], baseScore: 100, comboBonus: 50 },
  { id: 'math-sub-single-5', subject: 'math', operation: 'subtraction', digitLevel: 'single', levelIndex: 5, targetValue: 5, tileRange: [1, 9], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 60, starThresholds: [0, 15, 30], baseScore: 100, comboBonus: 50 },
  { id: 'math-sub-single-6', subject: 'math', operation: 'subtraction', digitLevel: 'single', levelIndex: 6, targetValue: [3, 6], tileRange: [1, 9], boardCols: 5, boardRows: 5, targetPairs: { 3: 5, 6: 5 }, constraint: 'time', constraintValue: 70, starThresholds: [0, 15, 30], baseScore: 100, comboBonus: 50 },
  { id: 'math-sub-single-7', subject: 'math', operation: 'subtraction', digitLevel: 'single', levelIndex: 7, targetValue: 5, tileRange: [1, 9], boardCols: 5, boardRows: 6, targetPairs: 12, constraint: 'time', constraintValue: 80, starThresholds: [0, 15, 30], baseScore: 100, comboBonus: 50 },
  // ── 뺄셈 2자리 Lv 8~14
  { id: 'math-sub-double-8', subject: 'math', operation: 'subtraction', digitLevel: 'double', levelIndex: 8, targetValue: 10, tileRange: [10, 99], boardCols: 4, boardRows: 4, targetPairs: 5, constraint: 'moves', constraintValue: 20, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-sub-double-9', subject: 'math', operation: 'subtraction', digitLevel: 'double', levelIndex: 9, targetValue: 20, tileRange: [10, 99], boardCols: 4, boardRows: 4, targetPairs: 6, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-sub-double-10', subject: 'math', operation: 'subtraction', digitLevel: 'double', levelIndex: 10, targetValue: 30, tileRange: [10, 99], boardCols: 4, boardRows: 5, targetPairs: 7, constraint: 'moves', constraintValue: 24, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-sub-double-11', subject: 'math', operation: 'subtraction', digitLevel: 'double', levelIndex: 11, targetValue: 50, tileRange: [10, 99], boardCols: 4, boardRows: 5, targetPairs: 8, constraint: 'moves', constraintValue: 26, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-sub-double-12', subject: 'math', operation: 'subtraction', digitLevel: 'double', levelIndex: 12, targetValue: 50, tileRange: [10, 99], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 70, starThresholds: [0, 15, 30], baseScore: 150, comboBonus: 75 },
  { id: 'math-sub-double-13', subject: 'math', operation: 'subtraction', digitLevel: 'double', levelIndex: 13, targetValue: [30, 50], tileRange: [10, 99], boardCols: 5, boardRows: 5, targetPairs: { 30: 5, 50: 5 }, constraint: 'time', constraintValue: 80, starThresholds: [0, 15, 30], baseScore: 150, comboBonus: 75 },
  { id: 'math-sub-double-14', subject: 'math', operation: 'subtraction', digitLevel: 'double', levelIndex: 14, targetValue: 50, tileRange: [10, 99], boardCols: 5, boardRows: 6, targetPairs: 12, constraint: 'time', constraintValue: 90, starThresholds: [0, 15, 30], baseScore: 150, comboBonus: 75 },
  // ── 뺄셈 3자리 Lv 15~20
  { id: 'math-sub-triple-15', subject: 'math', operation: 'subtraction', digitLevel: 'triple', levelIndex: 15, targetValue: 100, tileRange: [100, 999], boardCols: 4, boardRows: 4, targetPairs: 5, constraint: 'moves', constraintValue: 20, starThresholds: [0, 5, 10], baseScore: 200, comboBonus: 100 },
  { id: 'math-sub-triple-16', subject: 'math', operation: 'subtraction', digitLevel: 'triple', levelIndex: 16, targetValue: 200, tileRange: [100, 999], boardCols: 4, boardRows: 4, targetPairs: 6, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 200, comboBonus: 100 },
  { id: 'math-sub-triple-17', subject: 'math', operation: 'subtraction', digitLevel: 'triple', levelIndex: 17, targetValue: 300, tileRange: [100, 999], boardCols: 4, boardRows: 5, targetPairs: 7, constraint: 'moves', constraintValue: 24, starThresholds: [0, 5, 10], baseScore: 200, comboBonus: 100 },
  { id: 'math-sub-triple-18', subject: 'math', operation: 'subtraction', digitLevel: 'triple', levelIndex: 18, targetValue: 300, tileRange: [100, 999], boardCols: 5, boardRows: 5, targetPairs: 8, constraint: 'time', constraintValue: 80, starThresholds: [0, 15, 30], baseScore: 200, comboBonus: 100 },
  { id: 'math-sub-triple-19', subject: 'math', operation: 'subtraction', digitLevel: 'triple', levelIndex: 19, targetValue: 500, tileRange: [100, 999], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 90, starThresholds: [0, 15, 30], baseScore: 200, comboBonus: 100 },
  { id: 'math-sub-triple-20', subject: 'math', operation: 'subtraction', digitLevel: 'triple', levelIndex: 20, targetValue: 500, tileRange: [100, 999], boardCols: 5, boardRows: 6, targetPairs: 12, constraint: 'time', constraintValue: 100, starThresholds: [0, 15, 30], baseScore: 200, comboBonus: 100 },
  // ── 곱셈 구구단 2단~5단 Lv 1~8
  { id: 'math-mul-1', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 1, targetValue: [2,4,6,8,10,12,14,16,18], tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 5, constraint: 'moves', constraintValue: 20, starThresholds: [0, 5, 10], baseScore: 120, comboBonus: 60 },
  { id: 'math-mul-2', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 2, targetValue: [3,6,9,12,15,18,21,24,27], tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 6, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 120, comboBonus: 60 },
  { id: 'math-mul-3', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 3, targetValue: [4,8,12,16,20,24,28,32,36], tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 6, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 120, comboBonus: 60 },
  { id: 'math-mul-4', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 4, targetValue: [5,10,15,20,25,30,35,40,45], tileRange: [1, 9], boardCols: 4, boardRows: 5, targetPairs: 7, constraint: 'moves', constraintValue: 24, starThresholds: [0, 5, 10], baseScore: 120, comboBonus: 60 },
  { id: 'math-mul-5', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 5, targetValue: [2,4,6,8,10,12,14,16,18,3,6,9,12,15,18,21,24,27], tileRange: [1, 9], boardCols: 4, boardRows: 5, targetPairs: 8, constraint: 'moves', constraintValue: 26, starThresholds: [0, 5, 10], baseScore: 120, comboBonus: 60 },
  { id: 'math-mul-6', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 6, targetValue: [3,6,9,12,15,18,21,24,27,4,8,12,16,20,24,28,32,36], tileRange: [1, 9], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 60, starThresholds: [0, 15, 30], baseScore: 120, comboBonus: 60 },
  { id: 'math-mul-7', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 7, targetValue: [4,8,12,16,20,24,28,32,36,5,10,15,20,25,30,35,40,45], tileRange: [1, 9], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 70, starThresholds: [0, 15, 30], baseScore: 120, comboBonus: 60 },
  { id: 'math-mul-8', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 8, targetValue: [2,4,6,8,10,12,3,6,9,12,15,4,8,12,16,5,10,15,20], tileRange: [1, 9], boardCols: 5, boardRows: 6, targetPairs: 12, constraint: 'time', constraintValue: 80, starThresholds: [0, 15, 30], baseScore: 120, comboBonus: 60 },
  // ── 곱셈 구구단 6단~9단 Lv 9~16
  { id: 'math-mul-9',  subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 9,  targetValue: [6,12,18,24,30,36,42,48,54], tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 5, constraint: 'moves', constraintValue: 20, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-mul-10', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 10, targetValue: [7,14,21,28,35,42,49,56,63], tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 6, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-mul-11', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 11, targetValue: [8,16,24,32,40,48,56,64,72], tileRange: [1, 9], boardCols: 4, boardRows: 4, targetPairs: 6, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-mul-12', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 12, targetValue: [9,18,27,36,45,54,63,72,81], tileRange: [1, 9], boardCols: 4, boardRows: 5, targetPairs: 7, constraint: 'moves', constraintValue: 24, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-mul-13', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 13, targetValue: [6,12,18,24,30,36,42,48,54,7,14,21,28,35,42,49,56,63], tileRange: [1, 9], boardCols: 4, boardRows: 5, targetPairs: 8, constraint: 'moves', constraintValue: 26, starThresholds: [0, 5, 10], baseScore: 150, comboBonus: 75 },
  { id: 'math-mul-14', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 14, targetValue: [7,14,21,28,35,42,49,56,63,8,16,24,32,40,48,56,64,72], tileRange: [1, 9], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 70, starThresholds: [0, 15, 30], baseScore: 150, comboBonus: 75 },
  { id: 'math-mul-15', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 15, targetValue: [8,16,24,32,40,48,56,64,72,9,18,27,36,45,54,63,72,81], tileRange: [1, 9], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 80, starThresholds: [0, 15, 30], baseScore: 150, comboBonus: 75 },
  { id: 'math-mul-16', subject: 'math', operation: 'multiplication', digitLevel: 'single', levelIndex: 16, targetValue: [6,7,8,9,12,14,16,18,21,24,27,28,35,36,42,45,48,49,54,56,63,72,81], tileRange: [1, 9], boardCols: 5, boardRows: 6, targetPairs: 12, constraint: 'time', constraintValue: 90, starThresholds: [0, 15, 30], baseScore: 150, comboBonus: 75 },
  // ── 곱셈 두 자리 Lv 17~22
  { id: 'math-mul-17', subject: 'math', operation: 'multiplication', digitLevel: 'double', levelIndex: 17, targetValue: [12,15,18,21,24], tileRange: [2, 9], boardCols: 4, boardRows: 4, targetPairs: 5, constraint: 'moves', constraintValue: 20, starThresholds: [0, 5, 10], baseScore: 200, comboBonus: 100 },
  { id: 'math-mul-18', subject: 'math', operation: 'multiplication', digitLevel: 'double', levelIndex: 18, targetValue: [20,24,28,30,35], tileRange: [2, 9], boardCols: 4, boardRows: 4, targetPairs: 6, constraint: 'moves', constraintValue: 22, starThresholds: [0, 5, 10], baseScore: 200, comboBonus: 100 },
  { id: 'math-mul-19', subject: 'math', operation: 'multiplication', digitLevel: 'double', levelIndex: 19, targetValue: [36,40,42,45,48,49], tileRange: [2, 9], boardCols: 4, boardRows: 5, targetPairs: 7, constraint: 'moves', constraintValue: 24, starThresholds: [0, 5, 10], baseScore: 200, comboBonus: 100 },
  { id: 'math-mul-20', subject: 'math', operation: 'multiplication', digitLevel: 'double', levelIndex: 20, targetValue: [54,56,63,64,72,81], tileRange: [2, 9], boardCols: 5, boardRows: 5, targetPairs: 8, constraint: 'time', constraintValue: 80, starThresholds: [0, 15, 30], baseScore: 200, comboBonus: 100 },
  { id: 'math-mul-21', subject: 'math', operation: 'multiplication', digitLevel: 'double', levelIndex: 21, targetValue: [12,15,20,24,28,30,36,40,42,45], tileRange: [2, 9], boardCols: 5, boardRows: 5, targetPairs: 10, constraint: 'time', constraintValue: 90, starThresholds: [0, 15, 30], baseScore: 200, comboBonus: 100 },
  { id: 'math-mul-22', subject: 'math', operation: 'multiplication', digitLevel: 'double', levelIndex: 22, targetValue: [48,49,54,56,63,64,72,81], tileRange: [2, 9], boardCols: 5, boardRows: 6, targetPairs: 12, constraint: 'time', constraintValue: 100, starThresholds: [0, 15, 30], baseScore: 200, comboBonus: 100 },
];

export function getMathLevelsByOperation(operation: MathLevelConfig['operation']): MathLevelConfig[] {
  return MATH_LEVELS.filter((l) => l.operation === operation);
}

export function getMathLevelById(id: string): MathLevelConfig | undefined {
  return MATH_LEVELS.find((l) => l.id === id);
}
