import type { MatrixLevelConfig } from '../systems/logic/matrixReasoningTypes';

export const MATRIX_REASONING_LEVELS: MatrixLevelConfig[] = [
  // ── difficultyLevel 1: gridSize=2, 단일 속성 (matrix-1 ~ matrix-10) ──
  {
    id: 'matrix-1',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['color'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-2',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['shape'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-3',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['size'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-4',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['fill'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-5',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['rotation'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-6',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['color'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-7',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['shape'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-8',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['size'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-9',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['fill'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-10',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    activeAttributes: ['rotation'],
    choiceCount: 3,
    starThresholds: [3, 4, 5],
  },

  // ── difficultyLevel 2: gridSize=3, 이중 속성 (matrix-11 ~ matrix-20) ──
  {
    id: 'matrix-11',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['shape', 'color'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-12',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['shape', 'size'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-13',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['color', 'fill'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-14',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['size', 'fill'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-15',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['shape', 'rotation'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-16',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['color', 'rotation'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-17',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['shape', 'color'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-18',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['size', 'rotation'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-19',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['fill', 'rotation'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },
  {
    id: 'matrix-20',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    activeAttributes: ['shape', 'fill'],
    choiceCount: 4,
    starThresholds: [3, 4, 5],
  },

  // ── difficultyLevel 3: gridSize=3, 삼중 속성 (matrix-21 ~ matrix-30) ──
  {
    id: 'matrix-21',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['shape', 'color', 'fill'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-22',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['shape', 'size', 'rotation'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-23',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['color', 'size', 'fill'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-24',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['shape', 'color', 'size'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-25',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['color', 'fill', 'rotation'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-26',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['shape', 'fill', 'rotation'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-27',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['size', 'fill', 'rotation'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-28',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['shape', 'color', 'rotation'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-29',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['shape', 'size', 'fill'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
  {
    id: 'matrix-30',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    activeAttributes: ['color', 'size', 'rotation'],
    choiceCount: 4,
    starThresholds: [2, 3, 5],
  },
];

export function getMatrixLevel(id: string): MatrixLevelConfig | undefined {
  return MATRIX_REASONING_LEVELS.find(l => l.id === id);
}

export function getFirstMatrixLevelId(): string {
  return MATRIX_REASONING_LEVELS[0].id;
}
