import type { MatrixLevelConfig } from '../systems/logic/matrixReasoningTypes';

export const MATRIX_REASONING_LEVELS: MatrixLevelConfig[] = [
  // ── 입문 — 이모지 (matrix-1 ~ matrix-10) ─────────────────────
  {
    id: 'matrix-1',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    choiceCount: 3,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['category-cycle'], categories: ['fruit', 'animal'] },
  },
  {
    id: 'matrix-2',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    choiceCount: 3,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['category-cycle'], categories: ['animal', 'celestial'] },
  },
  {
    id: 'matrix-3',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    choiceCount: 3,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['sequence-shift'], categories: ['fruit'] },
  },
  {
    id: 'matrix-4',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 2,
    totalRounds: 5,
    timeLimit: 90,
    choiceCount: 3,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['sequence-shift'], categories: ['celestial'] },
  },
  {
    id: 'matrix-5',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 100,
    choiceCount: 3,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['category-cycle'], categories: ['fruit', 'animal', 'celestial'] },
  },
  {
    id: 'matrix-6',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 100,
    choiceCount: 3,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['category-cycle'], categories: ['vehicle', 'food', 'face'] },
  },
  {
    id: 'matrix-7',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 100,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['sequence-shift'], categories: ['fruit'] },
  },
  {
    id: 'matrix-8',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 100,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['sequence-shift'], categories: ['animal'] },
  },
  {
    id: 'matrix-9',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 110,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    emojiOpts: { patterns: ['count-progression'], categories: ['fruit'] },
  },
  {
    id: 'matrix-10',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 1,
    cellKind: 'emoji',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 110,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    emojiOpts: {
      patterns: ['category-cycle', 'sequence-shift'],
      categories: ['fruit', 'animal', 'celestial', 'vehicle', 'food', 'face'],
    },
  },

  // ── 중급 — 숫자 (matrix-11 ~ matrix-20) ──────────────────────
  {
    id: 'matrix-11',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['arith-row'], valueRange: [1, 30] },
  },
  {
    id: 'matrix-12',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['arith-col'], valueRange: [1, 30] },
  },
  {
    id: 'matrix-13',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 120,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['arith-row'], valueRange: [1, 40] },
  },
  {
    id: 'matrix-14',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 130,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['arith-both'], valueRange: [1, 30] },
  },
  {
    id: 'matrix-15',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 130,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['multiplication'], valueRange: [2, 81] },
  },
  {
    id: 'matrix-16',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 130,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['sum-corner'], valueRange: [1, 40] },
  },
  {
    id: 'matrix-17',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 140,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['geometric'], valueRange: [2, 64] },
  },
  {
    id: 'matrix-18',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 140,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['geometric'], valueRange: [3, 99] },
  },
  {
    id: 'matrix-19',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 140,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    numberOpts: { patterns: ['arith-row', 'arith-col'], valueRange: [1, 50] },
  },
  {
    id: 'matrix-20',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 2,
    cellKind: 'number',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    numberOpts: {
      patterns: ['arith-row', 'arith-both', 'multiplication', 'sum-corner', 'geometric'],
      valueRange: [1, 99],
    },
  },

  // ── 고급 — Set 카드 (matrix-21 ~ matrix-30) ──────────────────
  {
    id: 'matrix-21',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 130,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    setcardOpts: { activeAttributeCount: 1 },
  },
  {
    id: 'matrix-22',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 130,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    setcardOpts: { activeAttributeCount: 1 },
  },
  {
    id: 'matrix-23',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 130,
    choiceCount: 4,
    starThresholds: [3, 4, 5],
    setcardOpts: { activeAttributeCount: 1 },
  },
  {
    id: 'matrix-24',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    setcardOpts: { activeAttributeCount: 2 },
  },
  {
    id: 'matrix-25',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    setcardOpts: { activeAttributeCount: 2 },
  },
  {
    id: 'matrix-26',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 150,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    setcardOpts: { activeAttributeCount: 2 },
  },
  {
    id: 'matrix-27',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 180,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    setcardOpts: { activeAttributeCount: 3 },
  },
  {
    id: 'matrix-28',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 180,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    setcardOpts: { activeAttributeCount: 3 },
  },
  {
    id: 'matrix-29',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 180,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    setcardOpts: { activeAttributeCount: 3 },
  },
  {
    id: 'matrix-30',
    subject: 'logic',
    gameType: 'matrix-reasoning',
    difficultyLevel: 3,
    cellKind: 'setcard',
    gridSize: 3,
    totalRounds: 5,
    timeLimit: 180,
    choiceCount: 4,
    starThresholds: [2, 3, 5],
    setcardOpts: { activeAttributeCount: 3 },
  },
];

export function getMatrixLevel(id: string): MatrixLevelConfig | undefined {
  return MATRIX_REASONING_LEVELS.find(l => l.id === id);
}

export function getFirstMatrixLevelId(): string {
  return MATRIX_REASONING_LEVELS[0].id;
}
