import type { OddOneOutLevelConfig } from '../systems/logic/oddOneOutTypes';

export const ODD_ONE_OUT_LEVELS: OddOneOutLevelConfig[] = [
  // ── difficultyLevel 1: 타이머 없음, 4개 도형 (odd-1 ~ odd-10) ──
  {
    id: 'odd-1',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['color'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-2',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['shape'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-3',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['size'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-4',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['fill'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-5',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['color', 'shape'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-6',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['color'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-7',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['shape'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-8',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['size'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-9',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['fill'],
    starThresholds: [4, 5, 6],
  },
  {
    id: 'odd-10',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 1,
    shapeCount: 4,
    totalRounds: 6,
    timeLimit: null,
    allowedOddReasons: ['color', 'size'],
    starThresholds: [4, 5, 6],
  },

  // ── difficultyLevel 2: 120초, 4~5개 도형 (odd-11 ~ odd-20) ──
  {
    id: 'odd-11',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 4,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['fill', 'rotation'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-12',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 4,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['rotation'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-13',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 4,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['color', 'fill'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-14',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['shape', 'fill'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-15',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['size', 'rotation'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-16',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 4,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['fill', 'rotation'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-17',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['color', 'rotation'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-18',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 4,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['shape', 'rotation'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-19',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['size', 'fill'],
    starThresholds: [3, 4, 5],
  },
  {
    id: 'odd-20',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 2,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 120,
    allowedOddReasons: ['color', 'shape', 'fill'],
    starThresholds: [3, 4, 5],
  },

  // ── difficultyLevel 3: 150초, 5개 도형 (odd-21 ~ odd-30) ──
  {
    id: 'odd-21',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['chirality'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-22',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['compound'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-23',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['chirality', 'rotation'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-24',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['compound', 'chirality'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-25',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['chirality'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-26',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['compound'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-27',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['chirality', 'compound'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-28',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['compound', 'rotation'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-29',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['chirality', 'fill'],
    starThresholds: [2, 3, 5],
  },
  {
    id: 'odd-30',
    subject: 'logic',
    gameType: 'odd-one-out',
    difficultyLevel: 3,
    shapeCount: 5,
    totalRounds: 5,
    timeLimit: 150,
    allowedOddReasons: ['compound', 'chirality', 'rotation'],
    starThresholds: [2, 3, 5],
  },
];

export function getOddOneOutLevel(id: string): OddOneOutLevelConfig | undefined {
  return ODD_ONE_OUT_LEVELS.find(l => l.id === id);
}

export function getFirstOddLevelId(): string {
  return ODD_ONE_OUT_LEVELS[0].id;
}
