export type SpellingDifficulty = 'beginner' | 'elementary' | 'intermediate' | 'advanced';
export type SpellingCategory =
  | 'phoneme'       // 자모/받침 표기
  | 'common-word'   // 자주 틀리는 단어
  | 'spacing'       // 띄어쓰기 포함 표현
  | 'grammar'       // 어법 (되/돼, 로서/로써 등)
  | 'sai-siot';     // 사이시옷

export interface SpellingQuestion {
  id: string;
  sentence: string;       // 빈칸은 ___ 로 표시 (정확히 1회)
  correct: string;
  wrong: string;
  hint?: string;
  explanation: string;
  category: SpellingCategory;
  difficulty: SpellingDifficulty;
}

export const SPELLING_QUESTIONS: SpellingQuestion[] = [

  // ────────────────────────────────────────────────────────────
  // BEGINNER (입문) — 25문제 — phoneme: 받침/자모 표기
  // ────────────────────────────────────────────────────────────
  {
    id: 'sp-be-001',
    sentence: '봄에 예쁜 ___이 피었다',
    correct: '꽃',
    wrong: '꼿',
    hint: 'ㅊ 받침 단어',
    explanation: "'꽃'이 올바른 표기입니다. 발음이 [꼰]처럼 들려도 ㅊ 받침으로 씁니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-002',
    sentence: '연못에서 ___를 즐겼다',
    correct: '낚시',
    wrong: '낙시',
    hint: 'ㄱ 받침 + 시 연음',
    explanation: "'낚시'가 올바른 표기입니다. [낙씨]로 발음되지만 '낚'으로 씁니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-003',
    sentence: '할머니가 사과를 ___았다',
    correct: '깎',
    wrong: '깍',
    hint: '된소리 겹받침 ㄲ',
    explanation: "'깎았다'가 올바른 표기입니다. 된소리 ㄲ 받침을 씁니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-004',
    sentence: '교실이 ___어서 쾌적하다',
    correct: '넓',
    wrong: '널',
    hint: '겹받침 ㄼ',
    explanation: "'넓어서'가 올바른 표기입니다. '넓다'의 겹받침 ㄼ을 기억하세요.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-005',
    sentence: '팔이 너무 ___아서 소매가 길다',
    correct: '짧',
    wrong: '짤',
    hint: '겹받침 ㄼ',
    explanation: "'짧아서'가 올바른 표기입니다. '짧다'의 겹받침 ㄼ을 기억하세요.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-006',
    sentence: '책을 ___어서 내용을 파악했다',
    correct: '읽',
    wrong: '일',
    hint: '겹받침 ㄺ',
    explanation: "'읽어서'가 올바른 표기입니다. '읽다'의 겹받침 ㄺ은 뒤에 모음이 오면 두 소리가 모두 납니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-007',
    sentence: '물건의 ___이 비쌌다',
    correct: '값',
    wrong: '갑',
    hint: '겹받침 ㅄ',
    explanation: "'값'이 올바른 표기입니다. [갑]으로 발음되지만 겹받침 ㅄ을 씁니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-008',
    sentence: '별 ___이 밤하늘을 가득 채웠다',
    correct: '빛',
    wrong: '빚',
    hint: '빛(光) vs 빚(債)',
    explanation: "'빛'은 광(光), '빚'은 빌린 돈(債)입니다. 하늘에 빛나는 것은 '빛'입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-009',
    sentence: '은행에서 빌린 ___을 갚았다',
    correct: '빚',
    wrong: '빛',
    hint: '빚(債) vs 빛(光)',
    explanation: "'빚'은 빌린 돈(負債)을 뜻합니다. '빛'과 혼동하지 마세요.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-010',
    sentence: '하늘이 ___고 공기가 맑다',
    correct: '밝',
    wrong: '박',
    hint: '겹받침 ㄺ',
    explanation: "'밝고'가 올바른 표기입니다. '밝다'의 겹받침 ㄺ을 기억하세요.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-011',
    sentence: '새 신발이 발에 ___아서 불편하다',
    correct: '작',
    wrong: '짝',
    hint: '작다(小) vs 짝(pair)',
    explanation: "'작아서'가 올바른 표기입니다. '작다'는 크기가 적음, '짝'은 쌍(pair)입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-012',
    sentence: '논 옆 모래 ___에서 당근을 길렀다',
    correct: '밭',
    wrong: '받',
    hint: '밭(田) vs 받(receive)',
    explanation: "'밭'은 채소를 심는 농경지입니다. '받'은 동사 어간입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-013',
    sentence: '화분에 ___을 뿌렸다',
    correct: '흙',
    wrong: '흑',
    hint: '흙(土) vs 흑(黑)',
    explanation: "'흙'은 땅(土), '흑'은 검다는 뜻(黑)입니다. 화분에 뿌리는 것은 '흙'입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-014',
    sentence: '저녁 메뉴로 ___을 먹었다',
    correct: '닭볶음',
    wrong: '닥볶음',
    hint: '닭(겹받침 ㄺ)',
    explanation: "'닭볶음'이 올바른 표기입니다. '닭'의 겹받침 ㄺ은 뒤에 자음이 오면 ㄱ으로 발음됩니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-015',
    sentence: '날씨가 ___아서 창문을 열었다',
    correct: '더',
    wrong: '덥',
    hint: 'ㅂ 불규칙 활용',
    explanation: "'더워서'의 형태로 써야 하므로 여기 ___에는 '더'가 맞습니다. '덥다'의 ㅂ 불규칙 활용입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-016',
    sentence: '목이 ___아서 약을 먹었다',
    correct: '아파',
    wrong: '압아',
    hint: 'ㅍ 받침 + 아 연음',
    explanation: "'아파서'가 올바른 표기입니다. '아프다'의 어간 '아프'에서 ㅡ가 탈락합니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-017',
    sentence: '마당에 ___이 피어 있다',
    correct: '잡초',
    wrong: '잡쵸',
    hint: 'ㅊ 자음',
    explanation: "'잡초'가 올바른 표기입니다. '쵸'는 없는 한국어 음절입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-018',
    sentence: '문을 ___고 들어왔다',
    correct: '열',
    wrong: '여',
    hint: '열다(open)의 어간',
    explanation: "'열고'가 올바른 표기입니다. '열다'의 어간은 '열'입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-019',
    sentence: '운동을 ___아서 몸이 건강해졌다',
    correct: '해',
    wrong: '핮',
    hint: '하다 → 해서 활용',
    explanation: "'해서'가 올바른 표기입니다. '하다'의 활용형은 '해서'입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-020',
    sentence: '밥을 ___먹어야 한다',
    correct: '잘',
    wrong: '자ㄹ',
    hint: '부사 잘',
    explanation: "'잘'이 올바른 표기입니다. 부사로 쓰이는 '잘'은 한 글자입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-021',
    sentence: '학교까지 걸어서 ___이 걸렸다',
    correct: '십 분',
    wrong: '십분',
    hint: '수 관형사 + 단위명사 띄어쓰기',
    explanation: "'십 분'처럼 수 관형사 뒤 단위명사는 띄어 씁니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-022',
    sentence: '오늘은 기분이 ___다',
    correct: '좋',
    wrong: '죻',
    hint: '좋다(好)',
    explanation: "'좋다'가 올바른 표기입니다. '죻'은 없는 글자입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-023',
    sentence: '나무에서 ___이 떨어졌다',
    correct: '잎',
    wrong: '닙',
    hint: '잎(葉)',
    explanation: "'잎'이 올바른 표기입니다. [입]으로 발음되지만 '잎'으로 씁니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-024',
    sentence: '어머니가 ___을 지으셨다',
    correct: '밥',
    wrong: '밥밥',
    hint: '밥(食)',
    explanation: "'밥'이 올바른 표기입니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },
  {
    id: 'sp-be-025',
    sentence: '하늘에서 하얀 ___이 내렸다',
    correct: '눈',
    wrong: '눈눈',
    hint: '눈(雪)',
    explanation: "'눈'이 올바른 표기입니다. 눈(雪)은 하늘에서 내립니다.",
    category: 'phoneme',
    difficulty: 'beginner',
  },

  // ────────────────────────────────────────────────────────────
  // ELEMENTARY (기초) — 25문제 — 자주 틀리는 단어 (common-word)
  // ────────────────────────────────────────────────────────────
  {
    id: 'sp-el-001',
    sentence: '___ 그렇게 됐어',
    correct: '왠지',
    wrong: '웬지',
    hint: '왜(why) + ㄴ지',
    explanation: "'왠지'는 '왜인지'의 준말입니다. '웬지'는 틀린 표기입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-002',
    sentence: '___이 이런 일이 생겼지?',
    correct: '웬',
    wrong: '왠',
    hint: '웬 = 어떠한, 무슨',
    explanation: "'웬'은 '어떠한'의 뜻입니다. '왠'은 '왜인지'에만 씁니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-003',
    sentence: '이걸 ___?',
    correct: '어떡해',
    wrong: '어떻해',
    hint: '어떡하다 = 어떻게 하다',
    explanation: "'어떡해'는 '어떻게 해'의 준말입니다. '어떻해'는 틀린 표기입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-004',
    sentence: '이 문제를 ___ 풀어야 해?',
    correct: '어떻게',
    wrong: '어떡게',
    hint: '어떻게 = 어떠하게',
    explanation: "'어떻게'는 '어떠하게'의 준말입니다. '어떡게'는 틀린 표기입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-005',
    sentence: '___에 생각해보니 그게 맞는 것 같다',
    correct: '곰곰이',
    wrong: '곰곰히',
    hint: '-이 vs -히: 첩어는 -이',
    explanation: "'곰곰이'가 올바른 표기입니다. 첩어(반복어) 뒤에는 '-이'를 씁니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-006',
    sentence: '그것을 ___ 알아봤어',
    correct: '일찍이',
    wrong: '일찌기',
    hint: '일찍 + 이',
    explanation: "'일찍이'가 올바른 표기입니다. '일찍'에 '-이'를 붙입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-007',
    sentence: '방을 ___ 청소했다',
    correct: '깨끗이',
    wrong: '깨끗히',
    hint: '깨끗 + 이',
    explanation: "'깨끗이'가 올바른 표기입니다. 받침이 ㅅ인 경우 '-이'를 씁니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-008',
    sentence: '시험을 ___ 마쳤다',
    correct: '무사히',
    wrong: '무사이',
    hint: '무사(無事) + 히',
    explanation: "'무사히'가 올바른 표기입니다. 한자어 뒤에는 '-히'를 씁니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-009',
    sentence: '이 음식은 ___ 맛있다',
    correct: '정말',
    wrong: '정말로',
    hint: '정말 vs 정말로',
    explanation: "'정말'이 올바른 표기입니다. '정말로'도 맞지만 문장 흐름상 '정말'이 자연스럽습니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-010',
    sentence: '이 두 개를 ___하면 안 된다',
    correct: '혼동',
    wrong: '혼돈',
    hint: '혼동(混同) vs 혼돈(混沌)',
    explanation: "'혼동'은 뒤섞어 잘못 앎(混同), '혼돈'은 뒤죽박죽 상태(混沌)입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-011',
    sentence: '예전부터 전해 내려온 ___',
    correct: '옛날',
    wrong: '엣날',
    hint: '옛(舊) vs 엣',
    explanation: "'옛날'이 올바른 표기입니다. '엣날'은 없는 표기입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-012',
    sentence: '___부터 이 규칙이 있었다',
    correct: '예',
    wrong: '옛',
    hint: '예부터 = 이전부터',
    explanation: "'예부터'가 올바른 표기입니다. '예'는 '옛날'과 같은 뜻으로 홀로 쓸 때는 '예'입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-013',
    sentence: '한글은 ___ 만들어졌다',
    correct: '세종대왕이',
    wrong: '세종대왕께서',
    hint: '주어 + 서술어 호응',
    explanation: "'세종대왕이'도 맞지만 존경 표현으로 '세종대왕께서'가 더 정확합니다. 여기서는 일반 서술이므로 '세종대왕이'입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-014',
    sentence: '오늘 학교에서 ___ 시험을 봤다',
    correct: '받아쓰기',
    wrong: '바다쓰기',
    hint: '받아쓰기(받다 + 쓰기)',
    explanation: "'받아쓰기'가 올바른 표기입니다. '받다'의 연결형 '받아'에 '쓰기'를 붙입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-015',
    sentence: '가방이 너무 ___',
    correct: '무거워',
    wrong: '무거와',
    hint: 'ㅂ 불규칙: 무겁다 → 무거워',
    explanation: "'무거워'가 올바른 표기입니다. '무겁다'의 ㅂ 불규칙 활용으로 '무거워'가 됩니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-016',
    sentence: '날이 ___ 겨울이 왔다',
    correct: '추워',
    wrong: '추와',
    hint: 'ㅂ 불규칙: 춥다 → 추워',
    explanation: "'추워'가 올바른 표기입니다. '춥다'의 ㅂ 불규칙 활용입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-017',
    sentence: '살이 ___서 옷이 맞지 않는다',
    correct: '쪄',
    wrong: '쩌',
    hint: '찌다 → 쪄',
    explanation: "'쪄서'가 올바른 표기입니다. '찌다(살이 찌다)'의 활용형입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-018',
    sentence: '음식을 ___게 먹으면 건강에 나쁘다',
    correct: '짜',
    wrong: '짜게',
    hint: '형용사 어간 + 게',
    explanation: "'짜게'가 완전한 형태이지만 여기서는 ___에 '짜'를 넣어 '짜게'가 됩니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-019',
    sentence: '___에 만나자',
    correct: '이따가',
    wrong: '있다가',
    hint: '이따가(잠시 후) vs 있다가(있은 후에)',
    explanation: "'이따가'는 '조금 후에'라는 뜻입니다. '있다가'는 어딘가에 있다가 떠나는 맥락에 씁니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-020',
    sentence: '저는 그 말에 ___ 수가 없어요',
    correct: '동의할',
    wrong: '동의 할',
    hint: '동의하다 + ㄹ 수',
    explanation: "'동의할'이 올바른 표기입니다. 동사 어간에 '-ㄹ'을 붙여 씁니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-021',
    sentence: '우리가 선생님께 ___을 보냈다',
    correct: '감사 편지',
    wrong: '감사편지',
    hint: '감사(感謝) + 편지',
    explanation: "'감사 편지'처럼 의미 단위가 다른 명사는 띄어 씁니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-022',
    sentence: '저한테 ___주세요',
    correct: '가르쳐',
    wrong: '가르켜',
    hint: '가르치다 → 가르쳐',
    explanation: "'가르쳐'가 올바른 표기입니다. '가르키다'는 틀린 표기이고, 동사는 '가르치다'입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-023',
    sentence: '친구가 손가락으로 산을 ___',
    correct: '가리켰다',
    wrong: '가르쳤다',
    hint: '가리키다 → 가리켰다',
    explanation: "'가리켰다'가 올바른 표기입니다. '가리키다'는 방향을 손가락으로 나타냄입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-024',
    sentence: '나는 수학 ___이 약하다',
    correct: '실력',
    wrong: '실럭',
    hint: '실력(實力)',
    explanation: "'실력'이 올바른 표기입니다. '실럭'은 없는 표기입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },
  {
    id: 'sp-el-025',
    sentence: '그 사람은 매우 ___하다',
    correct: '부지런',
    wrong: '부즈런',
    hint: '부지런하다',
    explanation: "'부지런'이 올바른 표기입니다. '부즈런'은 없는 표기입니다.",
    category: 'common-word',
    difficulty: 'elementary',
  },

  // ────────────────────────────────────────────────────────────
  // INTERMEDIATE (중급) — 25문제 — 사이시옷 + 띄어쓰기
  // ────────────────────────────────────────────────────────────
  {
    id: 'sp-in-001',
    sentence: '___에 잘 자고 일어났다',
    correct: '하룻밤',
    wrong: '하루밤',
    hint: '사이시옷: 하루 + 밤',
    explanation: "'하룻밤'이 올바른 표기입니다. '하루'와 '밤'이 합쳐질 때 사이시옷이 들어갑니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-002',
    sentence: '아이들이 ___ 마당에서 뛰어놀았다',
    correct: '뒷',
    wrong: '뒤',
    hint: '뒷마당: 사이시옷',
    explanation: "'뒷마당'이 올바른 표기입니다. '뒤'와 '마당'이 합쳐지면 사이시옷이 들어갑니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-003',
    sentence: '___이 생겨서 방이 밝아졌다',
    correct: '햇빛',
    wrong: '해빛',
    hint: '해 + 빛 → 햇빛',
    explanation: "'햇빛'이 올바른 표기입니다. 순우리말 합성어에서 뒷말 첫소리가 된소리로 날 때 사이시옷을 씁니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-004',
    sentence: '___ 수를 세어보자',
    correct: '개수',
    wrong: '갯수',
    hint: '개수(個數): 한자어 합성어',
    explanation: "'개수'가 올바른 표기입니다. 두 한자어의 합성어에는 사이시옷을 쓰지 않습니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-005',
    sentence: '___으로 이사했다',
    correct: '윗층',
    wrong: '위층',
    hint: '윗층: 위 + 층',
    explanation: "'윗층'이 올바른 표기입니다. '위'와 '층'이 합쳐지면 사이시옷이 들어갑니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-006',
    sentence: '___이 없으면 길을 잃는다',
    correct: '이정표',
    wrong: '이정 표',
    hint: '이정표(里程標): 한 단어',
    explanation: "'이정표'는 한 단어이므로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-007',
    sentence: '그 일은 내가 ___ 수 없다',
    correct: '할',
    wrong: '할 ',
    hint: '할 수 없다',
    explanation: "'할 수 없다'가 올바릅니다. '할' 뒤에 '수'는 의존명사이므로 띄어 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-008',
    sentence: '___이 뜨겁게 내리쬔다',
    correct: '햇살',
    wrong: '해살',
    hint: '해 + 살 → 햇살',
    explanation: "'햇살'이 올바른 표기입니다. '해'와 '살'의 합성어에 사이시옷이 들어갑니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-009',
    sentence: '봄에는 ___이 여기저기 피었다',
    correct: '들꽃',
    wrong: '들 꽃',
    hint: '들꽃: 한 단어 합성어',
    explanation: "'들꽃'은 합성어이므로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-010',
    sentence: '___이 꽤 높다',
    correct: '나뭇가지',
    wrong: '나무가지',
    hint: '나무 + 가지 → 나뭇가지',
    explanation: "'나뭇가지'가 올바른 표기입니다. '나무'와 '가지'가 합쳐지며 사이시옷이 들어갑니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-011',
    sentence: '강의 ___ 건넜다',
    correct: '건너편을',
    wrong: '건너 편을',
    hint: '건너편: 한 단어',
    explanation: "'건너편'은 한 단어이므로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-012',
    sentence: '어제 ___ 잘 잤다',
    correct: '밤새',
    wrong: '밤 새',
    hint: '밤새: 부사(밤새도록)',
    explanation: "'밤새'는 '밤새도록'의 준말로 한 단어입니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-013',
    sentence: '___의 맛이 신선하다',
    correct: '냇물',
    wrong: '내물',
    hint: '내(川) + 물 → 냇물',
    explanation: "'냇물'이 올바른 표기입니다. '내'와 '물'의 합성어에 사이시옷이 들어갑니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-014',
    sentence: '바다에서 ___이 보였다',
    correct: '돛단배',
    wrong: '돛 단배',
    hint: '돛단배: 합성어',
    explanation: "'돛단배'는 합성어이므로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-015',
    sentence: '아이가 ___ 잠들었다',
    correct: '스르르',
    wrong: '스르륵',
    hint: '스르르(부드럽게)',
    explanation: "'스르르'가 올바른 표기입니다. '스르륵'은 다른 부사입니다.",
    category: 'common-word',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-016',
    sentence: '___을 찾아 떠났다',
    correct: '보물섬',
    wrong: '보물 섬',
    hint: '보물섬: 한 단어',
    explanation: "'보물섬'은 합성어로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-017',
    sentence: '___ 공부해서 시험을 잘 봤다',
    correct: '미리미리',
    wrong: '미리 미리',
    hint: '미리미리: 부사',
    explanation: "'미리미리'는 한 단어이므로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-018',
    sentence: '문을 ___를 눌렀다',
    correct: '초인종',
    wrong: '초인 종',
    hint: '초인종(招引鐘): 한 단어',
    explanation: "'초인종'은 한자어 합성어로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-019',
    sentence: '방 ___에 앉았다',
    correct: '한가운데',
    wrong: '한 가운데',
    hint: '한가운데: 부사/명사',
    explanation: "'한가운데'는 한 단어로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-020',
    sentence: '___를 따라 걸었다',
    correct: '오솔길',
    wrong: '오솔 길',
    hint: '오솔길: 합성어',
    explanation: "'오솔길'은 합성어로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-021',
    sentence: '강가의 ___에 앉았다',
    correct: '바윗돌',
    wrong: '바위돌',
    hint: '바위 + 돌 → 바윗돌',
    explanation: "'바윗돌'이 올바른 표기입니다. '바위'와 '돌'의 합성어에 사이시옷이 들어갑니다.",
    category: 'sai-siot',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-022',
    sentence: '저 ___ 새들이 날아간다',
    correct: '하늘가',
    wrong: '하늘 가',
    hint: '하늘가: 한 단어',
    explanation: "'하늘가'는 '하늘의 끝부분'을 뜻하는 합성어입니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-023',
    sentence: '그 아이는 ___이 맑다',
    correct: '눈빛',
    wrong: '눈 빛',
    hint: '눈빛: 합성어',
    explanation: "'눈빛'은 합성어로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-024',
    sentence: '사람들의 ___에 감동받았다',
    correct: '따뜻함',
    wrong: '따뜻 함',
    hint: '따뜻함: 명사형',
    explanation: "'따뜻함'은 형용사 '따뜻하다'의 명사형으로 붙여 씁니다.",
    category: 'spacing',
    difficulty: 'intermediate',
  },
  {
    id: 'sp-in-025',
    sentence: '사과나무 ___에 잘 익은 사과가 달렸다',
    correct: '가지',
    wrong: '갖이',
    hint: '가지(枝)',
    explanation: "'가지'가 올바른 표기입니다. '갖이'는 없는 표기입니다.",
    category: 'common-word',
    difficulty: 'intermediate',
  },

  // ────────────────────────────────────────────────────────────
  // ADVANCED (고급) — 25문제 — 어법/문법 (되/돼, 로서/로써 등)
  // ────────────────────────────────────────────────────────────
  {
    id: 'sp-ad-001',
    sentence: '왜 안 ___?',
    correct: '돼',
    wrong: '되',
    hint: '돼 = 되어, 어미 -아/어',
    explanation: "'돼'는 '되어'의 준말입니다. '되'는 어간으로 홀로 쓰이지 않습니다. '안 되어' → '안 돼'.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-002',
    sentence: '꿈이 이루어지길 바라면 포기하면 안 ___',
    correct: '된다',
    wrong: '됩니다',
    hint: '안 된다 (구어체)',
    explanation: "'안 된다'가 구어체에서 자연스럽습니다. '됩니다'도 맞지만 이 문맥에서는 '된다'가 어울립니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-003',
    sentence: '이 방법은 사용이 가능하게 ___',
    correct: '됩니다',
    wrong: '됩니까',
    hint: '평서문 vs 의문문',
    explanation: "'됩니다'는 평서문 어미, '됩니까'는 의문문 어미입니다. 이 문장은 평서문입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-004',
    sentence: '대표___서 한 마디 하겠습니다',
    correct: '로',
    wrong: '으로',
    hint: '로서: 자격/신분 표현',
    explanation: "'대표로서'가 올바른 표기입니다. 자격이나 신분을 나타낼 때는 '로서'를 씁니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-005',
    sentence: '펜___글을 쓰다',
    correct: '으로써',
    wrong: '으로서',
    hint: '로써: 수단/도구',
    explanation: "'펜으로써'가 올바른 표기입니다. 도구나 수단을 나타낼 때는 '로써'를 씁니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-006',
    sentence: '어제 공원에 ___ 친구를 만났다',
    correct: '갔다가',
    wrong: '갔다',
    hint: '갔다가: 갔다가 돌아오는 뜻',
    explanation: "'갔다가'는 어딘가에 갔다가 돌아오는 의미입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-007',
    sentence: '그때 내가 ___게 틀렸어',
    correct: '분명',
    wrong: '분명히',
    hint: '부사 위치',
    explanation: "두 가지 모두 쓸 수 있지만 '분명히'가 더 자연스럽습니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-008',
    sentence: '학생이 ___ 태도를 지켜야 한다',
    correct: '학생으로서',
    wrong: '학생으로써',
    hint: '로서(자격) vs 로써(수단)',
    explanation: "'학생으로서'가 올바릅니다. 자격을 나타낼 때는 '로서'입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-009',
    sentence: '___며칠이 남았어?',
    correct: '며칠',
    wrong: '몇일',
    hint: '며칠 = 몇 날',
    explanation: "'며칠'이 올바른 표기입니다. '몇일'은 틀린 표기입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-010',
    sentence: '그 일은 내가 ___ 아니야',
    correct: '한 게',
    wrong: '한게',
    hint: '한 것이 → 한 게',
    explanation: "'한 게'가 올바른 표기입니다. '것이'의 준말 '게' 앞은 의존명사이므로 띄어 씁니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-011',
    sentence: '눈이 많이 ___ 길이 미끄럽다',
    correct: '와서',
    wrong: '와서의',
    hint: '오다 → 와서',
    explanation: "'와서'가 올바릅니다. '오다'의 연결어미는 '와서'입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-012',
    sentence: '책을 ___ 중요한 내용을 메모했다',
    correct: '읽으면서',
    wrong: '읽는 면서',
    hint: '읽으면서 (동시 동작)',
    explanation: "'읽으면서'가 올바른 표기입니다. '-으면서'는 동시에 일어나는 동작을 나타냅니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-013',
    sentence: '그 영화는 나한테 ___ 좋았어',
    correct: '봤을 때',
    wrong: '봤는데',
    hint: '문맥상 어울리는 연결어',
    explanation: "여기서는 '봤을 때'가 더 자연스럽습니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-014',
    sentence: '오늘 공부를 ___ 내일 놀자',
    correct: '하고 나서',
    wrong: '하고나서',
    hint: '하고 나서: 띄어쓰기',
    explanation: "'하고 나서'가 올바른 표기입니다. '나서'는 보조용언이므로 띄어 씁니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-015',
    sentence: '그 사람은 의사가 ___',
    correct: '됐어',
    wrong: '됬어',
    hint: '되었어 → 됐어',
    explanation: "'됐어'가 올바른 표기입니다. '됬어'는 없는 표기입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-016',
    sentence: '그 말이 맞는지 ___ 모르겠어',
    correct: '안',
    wrong: '않',
    hint: '안(부정 부사) vs 않(아니하다 어간)',
    explanation: "'안 모르겠어'에서 '안'은 부정 부사입니다. '않'은 '아니하다'의 어간으로 '않다'처럼 씁니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-017',
    sentence: '약속을 지키지 ___겠다',
    correct: '않',
    wrong: '안',
    hint: '않겠다 = 아니 하겠다',
    explanation: "'않겠다'가 올바른 표기입니다. '아니하겠다'의 준말입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-018',
    sentence: '이 책을 ___ 알았는데 어렵다',
    correct: '쉬운 줄',
    wrong: '쉬운줄',
    hint: '쉬운 줄: 줄은 의존명사',
    explanation: "'쉬운 줄'이 올바른 표기입니다. '줄'은 의존명사이므로 앞말과 띄어 씁니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-019',
    sentence: '어린 시절에 놀___기억이 있다',
    correct: '던',
    wrong: '든',
    hint: '던(과거 회상) vs 든(선택)',
    explanation: "'놀던'은 과거 회상을 나타냅니다. '든'은 '밥이든 빵이든' 같은 선택 의미입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-020',
    sentence: '밥___빵이든 뭐든 좋아',
    correct: '이든',
    wrong: '이던',
    hint: '든(선택) vs 던(회상)',
    explanation: "'이든'은 선택의 의미입니다. '이던'은 과거를 회상하는 의미입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-021',
    sentence: '그 문제가 어___고 했어',
    correct: '렵다',
    wrong: '렵다고',
    hint: '어렵다고 했어',
    explanation: "'어렵다고 했어'가 올바릅니다. ___에는 '렵다'가 들어가 '어렵다고'가 됩니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-022',
    sentence: '합격할 ___이 보이지 않는다',
    correct: '것',
    wrong: '거',
    hint: '것(의존명사) 문어체',
    explanation: "문어체에서는 '것'이 올바릅니다. '거'는 구어체에서 씁니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-023',
    sentence: '그 소식을 들은 ___가 어제였다',
    correct: '게',
    wrong: '것이',
    hint: '것이 → 게 (구어체)',
    explanation: "구어체에서 '것이'는 '게'로 줄어듭니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-024',
    sentence: '이제 좀 살___같다',
    correct: '것',
    wrong: '거',
    hint: '것 같다 (문어체)',
    explanation: "'살 것 같다'가 문어체에서 올바른 표기입니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
  {
    id: 'sp-ad-025',
    sentence: '그 일은 네가 책임지___야 한다',
    correct: '어야',
    wrong: '아야',
    hint: '지다 → 지어야',
    explanation: "'책임지어야'의 준말이 '책임져야'입니다. ___에 '어야'가 들어갑니다.",
    category: 'grammar',
    difficulty: 'advanced',
  },
];

export function getQuestionsByDifficulty(difficulty: SpellingDifficulty): SpellingQuestion[] {
  return SPELLING_QUESTIONS.filter(q => q.difficulty === difficulty);
}
